<?xml version="1.0" encoding="UTF-8"?>
<Project>
    <Project_Created_Time>2018-12-13 10:32:12</Project_Created_Time>
    <TD_Version>4.2.217</TD_Version>
    <UCode>10101110</UCode>
    <Name>picorv32-wb-test</Name>
    <HardWare>
        <Family>EG4</Family>
        <Device>EG4S20BG256</Device>
    </HardWare>
    <Source_Files>
        <Verilog>
            <File>picorv32_wrapper.v</File>
            <File>top.v</File>
            <File>wb_intercon.v</File>
            <File>uart16550_1.5.4/rtl/verilog/raminfr.v</File>
            <File>uart16550_1.5.4/rtl/verilog/uart_receiver.v</File>
            <File>uart16550_1.5.4/rtl/verilog/uart_regs.v</File>
            <File>uart16550_1.5.4/rtl/verilog/uart_rfifo.v</File>
            <File>uart16550_1.5.4/rtl/verilog/uart_sync_flops.v</File>
            <File>uart16550_1.5.4/rtl/verilog/uart_tfifo.v</File>
            <File>uart16550_1.5.4/rtl/verilog/uart_top.v</File>
            <File>uart16550_1.5.4/rtl/verilog/uart_transmitter.v</File>
            <File>uart16550_1.5.4/rtl/verilog/uart_wb.v</File>
            <File>wb_intercon_1.1/rtl/verilog/wb_mux.v</File>
            <File>wb_ram_1.0/rtl/verilog/wb_ram.v</File>
            <File>al_ip/al_ip_bram_simple_dual_emb9k_4kbyte.v</File>
            <File>wb_ram_al_bram.v</File>
            <File>sdram_al_eg4s20.v</File>
            <File>sdr_ctrl/rtl/core/sdrc_bank_ctl.v</File>
            <File>sdr_ctrl/rtl/core/sdrc_bank_fsm.v</File>
            <File>sdr_ctrl/rtl/core/sdrc_bs_convert.v</File>
            <File>sdr_ctrl/rtl/core/sdrc_core.v</File>
            <File>sdr_ctrl/rtl/core/sdrc_define.v</File>
            <File>sdr_ctrl/rtl/core/sdrc_req_gen.v</File>
            <File>sdr_ctrl/rtl/core/sdrc_xfr_ctl.v</File>
            <File>sdr_ctrl/rtl/top/sdrc_top.v</File>
            <File>sdr_ctrl/rtl/wb2sdrc/wb2sdrc.v</File>
            <File>sdr_ctrl/rtl/lib/async_fifo.v</File>
            <File>sdr_ctrl/rtl/lib/sync_fifo.v</File>
        </Verilog>
        <ADC_FILE>io.adc</ADC_FILE>
        <SDC_FILE>clocks.sdc</SDC_FILE>
        <CWC_FILE/>
    </Source_Files>
    <TOP_MODULE>
        <LABEL/>
        <MODULE>top</MODULE>
        <CREATEINDEX>user</CREATEINDEX>
    </TOP_MODULE>
    <Project_Settings>
        <Step_Last_Change>2018-12-13 11:08:23</Step_Last_Change>
        <Current_Step>60</Current_Step>
        <Step_Status>true</Step_Status>
    </Project_Settings>
</Project>
